# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: .

      - name: Terraform Validate
        run: terraform init -backend=false && terraform validate
        working-directory: .

  Ansible-init:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Ansible collections
        run: ansible-galaxy collection install community.general

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Run TFLint
        run: tflint --init && tflint --recursive
        working-directory: .


  # Checkov:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     security-events: write
  #   steps:
  #       - uses: actions/checkout@v4

  #       - name: Checkov Action
  #         uses: bridgecrewio/checkov-action@v12
  #         with:
  #           output_format: cli,sarif
  #           output_file_path: console,results.sarif

  #       - name: Upload SARIF file
  #         uses: github/codeql-action/upload-sarif@v3
  #         if: success() || failure()
  #         with:
  #           sarif_file: results.sarif
